
# The log file to write.
log_file: isyhelper.log
# log level can be debug or info
# debug will produce a lot of output so watch or disk space!
log_level: info

# Default host is the default ip address of the currnet host
# If you have multiple interfaces you can set which one
# Otherwise don't define it.
host: 
# Default port is 8080 for the local REST interface
port: 

# To run the webserver with SSL, add your info.
# But, to use with Maker, this can not be a self-signed certificate :-(
#ssl:
#  certificate: /home/pi/ssl/myserver.crt
#  private_key: /home/pi/ssl/myserver_nopass.key

# TODO: Make it all under isy:
# Your isy configuration
isy:
  host: 192.168.1.64
  port: 80
  user: someuser
  password: somepassword
  # TODO: Add configurable prefix
  # All variables in the ISY will be prefixed with this.
  # variable_prefix: s.IH.

ifttt:
  # From: https://ifttt.com/maker
  # Your secret key is:
  maker_secret_key: ThisShouldBeYourMakerSecretkey

# Helpers
helpers:

  - name: DateAndTime
    type: DateAndTime
    # second,minute,hour,day
    level: minute

  # The name and type must currently be Maker!
  # In IFTT, set
  # url: http://your_host_ip:your_outside_port/maker
  # Method: POST
  # Content Type: application/json
  # Body: { "token" : "my_secret_token", "type" : "variable", "name" : "your_variable_name", "value" : "the_value" }
  - name: Maker
    type: Maker
    # Anything you chose.
    token: my_secret_token

  - name: Test
    ip: 192.168.1.60
    type: Test
    port: not_defined
    model: not_defined
    user: not_defined
    password: not_defined

  - name: MyCamera
    ip: 192.168.1.110
    port: 80
    type: Foscam1
    model: foscam
    user: someuser
    password: somepassword

  - name: PyHue
    type: PyHue
    # If this is true it will register all devices with a spoken property
    use_spoken: true
    # Default host is current, only set if you need a different ip
    host: 
    # 8081 is the default, change if you have something else running on that port
    http_port: 8081

  # The Belkin WeMo emulator
  - name: FauxMo
    type: FauxMo
    # If this is true it will register all devices with a spoken property
    # It is better to use the PyHue helper for this instead.
    use_spoken: false
    devices:
      - name: Kitchen Lights
        address: A1 B1 C1  1
        type: ISY
      - name: Family Room Table
        address: A2 B2 C2 1
        type: ISY
      - name: TV
        type: Maker
        on_event:  family_room_watch_tv
        off_event: family_room_av_off
      - name: Chromecast
        type: Maker
        on_event:  family_room_watch_chromecast
        off_event: family_room_av_off

  # A Harmony Hub
  # This will track the current activity in the ISY state variable
  #  s.IH.MyHarmony.CurrentActivity
  # You must make sure the variable exists as a state variable!
  - name: MyHarmony
    type: PyHarmony
    # Harmony Hub IP address
    host: 192.168.1.75
    port: 5222
    # Harmony Hub login email
    email: you@somwhere.com
    # Harmony Hub login password
    password: your_harmony_password
